[package]
name = "monomo-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.36"
syn = {version = "1.0.86", features = ["extra-traits", "derive", "full"]}
quote = "1.0.15"